[server]
port = 8501
enableCORS = false
headless = true

[theme]
primaryColor = "#333333"  # Dark Gray for primary theme
backgroundColor = "#121212"  # Dark background
secondaryBackgroundColor = "#1f1f1f"  # Slightly lighter dark gray
textColor = "#ffffff"  # White text for contrast
font = "sans serif"
